name = "uno"
main = "src/server.js"
workers_dev = true
compatibility_date = "2021-11-08"
# Add your account ID here
account_id = ""

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
]

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]
